#!/usr/bin/env bash
# Configures Nginx server to have a custom 404 page.
# The page contains the string "Ceci n'est pas une page".

sudo apt-get update
sudo apt-get -y install nginx

# redirecting to 'redirect_me' page
sudo sh -c 'echo "Hello World!" > /var/www/html/index.html'
string_replace="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/AAteddy permanent;"
sudo sed -i "s/server_name _;/$string_replace/" /etc/nginx/sites-enabled/default

# creating a custom 404 error page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
string_to_replace="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\troot \/var/www/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$string_to_replace/" /etc/nginx/sites-enabled/default

sudo service nginx restart
