#!/usr/bin/env bash
# Installs HAProxy version 2.8 with the following configurations:
#+    Enables management via the init script.
#+    Distributes requests using a round-robin algorithm.

# Install and configure HAproxy on my lb-01 server
sudo apt-get install -y software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.8
sudo apt-get update
sudo apt-get install -y haproxy=2.8.\*

# Edit haproxy.cfg configuration file
server_config=\
"
frontend teddy_frontend
	bind *:80
	mode http
	default_backend teddy_backend
backend teddy_backend
	balance roundrobin
	server 309825-web-01 54.152.182.43:80 check
	server 309825-web-02 100.25.196.17:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# Enable haproxy to be started by init script
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

# Testing the Haproxy configuration file
sudo haproxy -c -f /etc/haproxy/haproxy.cfg

# Restart the haproxy service
sudo service haproxy restart
