#!/usr/bin/env bash
# Displays the content of the file /etc/passwd.
#   It only displays: username, user id, and home directory path

while read passwd; do
	echo "$passwd" | cut -d ':' -f1,3,6
done < "/etc/passwd"
