#!/usr/bin/env bash
# Configures a ufw firewall to block all incoming traffic
#+ except for TCP ports 22, 443 and 80.

sudo apt-get -y update
sudo apt-get -y install ufw

# make sure the value of IPV6 is set to yes
sudo sed -i 's/IPV6=.*/IPV6=yes/' /etc/default/ufw
sudo ufw disable
sudo ufw default deny incoming
sudo ufw default allow outgoing

# Allow incoming traffic on TCP ports 22, 443, and 80 by running
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp

sudo ufw enable

# check configuration status to make sure its all set
sudo ufw status
