#!/usr/bin/env bash
# Configure ssh client so that you can connect to a
# server without typing a password.
Host school
    HostName 54.152.182.43
    User ubuntu
    IdentityFile ~/.ssh/school
    PasswordAuthentication no
